# Generated by Django 3.2.5 on 2021-07-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('diary', models.TextField()),
                ('public', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Diaries',
            },
        ),
    ]
