# Generated by Django 3.2.5 on 2021-07-30 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('goodwords', models.TextField()),
                ('speaker', models.CharField(max_length=120)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodwords', to='calendars.calendar')),
            ],
            options={
                'verbose_name_plural': 'Good Words',
            },
        ),
        migrations.CreateModel(
            name='BackgroundPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('goodword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='goodwords.goodword')),
            ],
        ),
    ]
